name: Deploy to Heroku Development

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
        env:
          FRAYT_FONT_AWESOME_TOKEN: ${{secrets.FRAYT_FONT_AWESOME_TOKEN}}
      - run: npm run check-format
        env:
          FRAYT_FONT_AWESOME_TOKEN: ${{secrets.FRAYT_FONT_AWESOME_TOKEN}}
      - run: npm test
        env:
          FRAYT_FONT_AWESOME_TOKEN: ${{secrets.FRAYT_FONT_AWESOME_TOKEN}}
      - run: CI=true npm run build
        env:
          FRAYT_FONT_AWESOME_TOKEN: ${{secrets.FRAYT_FONT_AWESOME_TOKEN}}
  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy to Staging
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'frayt-web-development'
          heroku_email: 'elijah@frayt.com'
  update_config:
    if: github.ref == 'refs/heads/master'
    name: Configure
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Release Version
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:set REACT_APP_RELEASE_VERSION="${{ github.sha }}" -a frayt-web-staging
